import "./components/select.js";
// import "./components/tabs.js";
import "./components/sliders.js";
import "./components/fancy.js";
import "./components/mobile-drop.js";
import "./components/modals.js";
import "./components/modals-types.js";
import "./components/popups.js";
import "./components/validator.js";
import "./components/types-content.js";
import "./components/popup-hint.js";
